apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-script
  namespace: keycloak
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
    name: nb-isolator
    namespace: keycloak
spec:
  concurrencyPolicy: Replace
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: nb-isolator
        spec:
          restartPolicy: OnFailure
          containers:
          - name: kube-cron-job
            image: change-to-keycloak-script-image
            args: ["setting-up-isolated-env-optimistically.sh"]
            volumeMounts:
            - name: keycloak-script
              mountPath: /keycloak-script
          imagePullSecrets:
           - name: docker-hub-secret 
          volumes:
          - name: keycloak-script
            persistentVolumeClaim:
              claimName: keycloak-script
          serviceAccount: cronjob
          serviceAccountName: cronjob
