apiVersion: v1
kind: ServiceAccount
metadata:
  name: cronjob
  namespace: keycloak
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: all-access-for-cron
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: all-access-for-cron-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: all-access-for-cron
subjects:
- kind: ServiceAccount
  name: cronjob
  namespace: keycloak
