apiVersion: v1
kind: ServiceAccount
metadata:
  name: jupy-api
  namespace: kubeflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: all-access
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: all-access-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: all-access
subjects:
- kind: ServiceAccount
  name: jupy-api
  namespace: kubeflow
---  
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jupyter-api
  name: katonic-service-api
  namespace: kubeflow
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: jupyter-api
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jupyter-api
  name: katonic-service-api
  namespace: kubeflow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jupyter-api
  template:
    metadata:
      labels:
        app: jupyter-api
    spec:
      containers:
      - image: katonic/service-api:latest
        imagePullPolicy: IfNotPresent
        name: jupter-notebook-apis
      imagePullSecrets:
      - name: docker-hub-secret
      serviceAccount: jupy-api
      serviceAccountName: jupy-api
