apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test
  name: test
  namespace: keycloak
spec:
  containers:
  - args:
    - "100000"
    command:
    - sleep
    image: katonic/nb-isolation:optimistic-1.3-with-minio-try
    imagePullPolicy: IfNotPresent
    name: test
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: cronjob-token-jq5vx
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: docker-hub-secret
  nodeName: aks-nodepool1-41024926-vmss000001
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: cronjob
  serviceAccountName: cronjob
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: cronjob-token-jq5vx
    secret:
      defaultMode: 420
      secretName: cronjob-token-jq5vx
