apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minio
    role: console
  name: minio-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
      role: console
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
        role: console 
    spec:
      containers:
      - args:
        - server 
        - /data{1...4}
        env:
        - name: CONSOLE_IDP_URL
          value: "https://torrent.katonic.ai/auth/realms/katonic/.well-known/openid-configuration" # Your external identity provide URL
        - name: CONSOLE_IDP_CLIENT_ID
          value: "myapp"
        - name: CONSOLE_IDP_SECRET
          value: c8b01721-ebee-4d33-8072-861f53166a34
        - name: CONSOLE_IDP_CALLBACK
          value: "https://torrent.katonic.ai/oauth_callback" 
        - name: CONSOLE_MINIO_SERVER
          value: http://minio-server.default.svc.cluster.local:9000
        image: katonic/katonic-mlops-enterprise-filebrowser:4.2
        imagePullPolicy: IfNotPresent
        name: minio-console
        volumeMounts:
        - mountPath: /root/.console/certs/CAs
          name: console-certs
        ports:
        - containerPort: 9090
          name: console
          protocol: TCP
        resources:
          requests:
            cpu: 20m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      imagePullSecrets:
        - name: docker-hub-secret
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes: 
      - name: console-certs
        secret:
          secretName: minio-certs


---
apiVersion: v1
kind: Service
metadata:
  name: minio-console
  labels:
    app: minio
    role: console
spec:
  selector:
    app: minio
    role: console
  type: ClusterIP
  ports:
   - port: 9001
     targetPort: 9090
     name: console

