apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-storage-pvc
  namespace: kubeflow
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: storage-class-name 
  resources:
    requests:
      storage: 10Gi
